# Copyright (c) 2025, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Handles the results of a single app generated by a core tool run"""

from dataclasses import dataclass, field
from functools import cached_property
from typing import Optional, List

import pandas as pd

from spark_rapids_tools import CspPathT
from spark_rapids_tools.enums import AppCoreStatusEnum


@dataclass
class QualificationLedger(object):
    ctxt: dict = field(default_factory=dict, init=False)


@dataclass
class AppDescriptor(object):
    """
    The main app descriptor that can be loaded from the core output.
    It should contain at least the eventlog_path and status
    """
    eventlog_path: str
    status: AppCoreStatusEnum
    ledger: QualificationLedger = field(default=None, init=False)
    qualified: bool = field(default=False, init=False)
    notes: dict = field(
        default_factory=lambda: {
            'disqualify': None,
            'line2': None,
            'etc': None
        }, init=False)

    @cached_property
    def is_successful(self) -> bool:
        return self.status == AppCoreStatusEnum.SUCCESS

    def set_as_qualified(self):
        self.qualified = True

    def disqualify(self, reason: str) -> None:
        return None

    def __post_init__(self):
        self.qualified = self.is_successful()


@dataclass
class AppHandler(AppDescriptor):
    """Handles the results generated by an app core tool run"""
    app_name: str
    app_id: str
    attempt_id: int
    root_path: CspPathT
    # we should fill the ones below as well
    # eventlog_path: str
    # result_path: CspPathT

    @cached_property
    def uuid(self) -> str:
        return self.app_id

    def convert_to_str(self) -> str:
        return f'AppHandler(app_name={self.app_name}, app_id={self.app_id}, attempt_id={self.attempt_id})'

    def load_df(self, file_label: str, cols: Optional[List[str]] = None) -> Optional[pd.DataFrame]:
        # get the actual_relative path for that label
        csv_file_path = self.root_path.create_sub_path(file_label)
        if not csv_file_path.exists():
            return None
        with csv_file_path.open_input_stream() as stream:
            df = pd.read_csv(stream)
            # select columns
            if cols:
                df = df[cols]
            return df
