# Copyright (c) 2025, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Handles the results generated by a qualification core tool run"""

from dataclasses import dataclass, field
from logging import Logger
from typing import List

import pandas as pd

from spark_rapids_pytools.common.utilities import ToolLogging, Utils
from spark_rapids_tools import CspPathT
from spark_rapids_tools.tools.core.app_handler import AppHandler, AppDescriptor
import yaml
from dataclasses import dataclass
from typing import List, Optional
from pathlib import Path


@dataclass
class QualCoreTableColumn:
    """Represents a column definition in a qualification table."""
    name: str
    data_type: str
    description: str

@dataclass
class QualCoreTableDef:
    """Represents a qualification table definition from qual-metrics.yaml."""
    label: str
    description: Optional[str]
    file_name: str
    file_format: str
    scope: str
    columns: List[QualCoreTableColumn]

    def is_per_app(self) -> bool:
        """Check if this table is per-application scope."""
        return self.scope == 'per-app'

    def is_global(self) -> bool:
        """Check if this table is global scope."""
        return self.scope == 'global'

class QualCoreTableLoader:
    """Loads qualification table definitions from qual-metrics.yaml."""

    def __init__(self, config_path: str):
        """Initialize with path to qual-metrics.yaml"""
        self.config_path = config_path

    def load_tables(self) -> List[QualCoreTableDef]:
        """Load all table definitions from the YAML file."""
        with open(self.config_path, 'r') as f:
            config = yaml.safe_load(f)

        table_defs = []
        for entry in config.get('qualTableDefinitions', []):
            columns = [
                QualCoreTableColumn(
                    name=col.get('name'),
                    data_type=col.get('dataType'),
                    description=col.get('description')
                )
                for col in entry.get('columns', [])
            ]

            table_def = QualCoreTableDef(
                label=entry.get('label'),
                description=entry.get('description'),
                file_name=entry.get('fileName'),
                file_format=entry.get('fileFormat'),
                scope=entry.get('scope'),
                columns=columns
            )
            table_defs.append(table_def)

        return table_defs

    def get_per_app_tables(self) -> List[QualCoreTableDef]:
        """Get only per-application scope tables."""
        return [t for t in self.load_tables() if t.is_per_app()]

    def get_global_tables(self) -> List[QualCoreTableDef]:
        """Get only global scope tables."""
        return [t for t in self.load_tables() if t.is_global()]


@dataclass
class QualCoreHandler(object):
    """Handles the results generated by a qualification core tool run"""
    result_path: CspPathT
    app_handlers: List[AppHandler] = field(default_factory=list, init=False)
    qual_core_tbl_mgr: QualCoreTableLoader = field(default=None, init=False)
    logger: Logger = field(default=None, init=False)

    def is_empty_result(self) -> bool:
        return not self.result_path.exists()

    def __load_app_handlers(self, app_summarys_df: pd.DataFrame) -> List[AppHandler]:
        loaded_app_handlers = []
        for _, row in app_summarys_df.iterrows():
            app_handler = AppHandler(
                app_name=row['App Name'],
                app_id=row['App ID'],
                attempt_id=row['Attempt ID'])
            loaded_app_handlers.append(app_handler)
        return loaded_app_handlers

    def _load_global_table(self, table_lbl: str) -> Optional[pd.DataFrame]:
        table_def = self.qual_core_tbl_mgr.get_global_tables().find(lambda t: t.label == table_lbl)
        if not table_def:
            return None
        csv_file_path = self.result_path.create_sub_path(table_def.file_name)
        if not csv_file_path.exists():
            return None
        with csv_file_path.open_input_stream() as stream:
            return pd.read_csv(stream)


    def __post_init__(self):
        # first the summary.csv which is the entry to all successfully processed files
        if self.result_path.exists():
            # first load, the appStatus.csv
            # for each row, we will have appHandler for successful apps, and otherwise, we will
            # have a failedAppDescriptor
            self.qual_core_tbl_mgr = QualCoreTableLoader(Utils.resource_path('core/qual-metrics.yaml'))
            summary_csv = self.result_path.create_sub_path('qual_core_output/apps_summary.csv')
            with summary_csv.open_input_stream() as stream:
                summary_df = pd.read_csv(stream)
                self.app_handlers.extend(self.__load_app_handlers(summary_df))
        print(summary_df)
        self.logger = ToolLogging.get_and_setup_logger(f'rapids.tools.{self.__class__.__name__}')

    def dump_output_path(self) -> None:
        self.logger.info(
            f'Qualification core output path: {self.result_path}: {self.result_path.exists()}')
        self.logger.info('application handlers:\n')
        self.logger.info(f'\t{Utils.gen_multiline_str([app_h.convert_to_str() for app_h in self.app_handlers])}')
